# Generated by Django 4.2 on 2023-04-30 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Store',
            new_name='store',
        ),
    ]
