# Generated by Django 4.2.14 on 2025-01-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_options_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='affiliate_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='affiliate_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
