# Generated by Django 4.2.14 on 2025-01-18 06:25

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_affiliate_link_product_affiliate_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_affiliate_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='cover_image'),
        ),
    ]
