# Generated by Django 4.2.14 on 2025-01-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_amazon_affiliate_id_product_image_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amazon_affiliate_id',
        ),
        migrations.AddField(
            model_name='store',
            name='amazon_affiliate_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
