# Generated by Django 4.2.14 on 2025-01-23 23:24

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cover_image', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='templates')),
                ('url', models.URLField(max_length=1000)),
                ('typ', models.CharField(choices=[('store', 'store'), ('blog', 'blog'), ('portfolio', 'portfolio')], max_length=100)),
                ('template', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='store',
            name='app',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='store_logos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='affiliate_link',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.template'),
        ),
    ]
