# Generated by Django 4.2.14 on 2025-01-24 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_category_product_cls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='blog',
            new_name='store',
        ),
    ]
