# Generated by Django 4.2.14 on 2025-01-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_profile_coins'),
        ('store', '0015_rename_blog_category_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='savers',
            field=models.ManyToManyField(blank=True, null=True, related_name='savers', to='Accounts.profile'),
        ),
    ]
