# Generated by Django 4.2.14 on 2025-01-29 20:29

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_profile_coins'),
        ('store', '0017_alter_product_original_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='cover_image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='savers',
            field=models.ManyToManyField(blank=True, related_name='savers', to='Accounts.profile'),
        ),
    ]
