# Generated by Django 4.2.14 on 2025-02-01 07:47

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_cover_image_alter_product_savers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_link',
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(default=1, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='cover_image'),
            preserve_default=False,
        ),
    ]
