# Generated by Django 4.2.14 on 2025-02-02 08:07

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_product_image_link_alter_product_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='typ',
        ),
        migrations.AddField(
            model_name='template',
            name='gif',
            field=models.ImageField(default=1, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='tempgifs'),
            preserve_default=False,
        ),
    ]
