# Generated by Django 4.2.14 on 2025-02-18 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_profile_coins'),
        ('store', '0020_remove_template_typ_template_gif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.profile'),
        ),
    ]
