# Generated by Django 4.2.14 on 2025-02-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_store_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
