# Generated by Django 4.2.14 on 2025-04-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
