# Generated by Django 5.2.3 on 2025-07-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coins',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
