# Generated by Django 4.1.7 on 2023-04-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_profile_coins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_new',
            new_name='unlimited',
        ),
    ]
