# Generated by Django 4.1.7 on 2023-04-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_rename_is_new_profile_unlimited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coins',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
