# Generated by Django 4.2 on 2023-04-28 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heading',
            name='element',
        ),
        migrations.RemoveField(
            model_name='image',
            name='element',
        ),
        migrations.RemoveField(
            model_name='link',
            name='element',
        ),
        migrations.RemoveField(
            model_name='list',
            name='element',
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='element',
        ),
        migrations.AddField(
            model_name='element',
            name='heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.heading'),
        ),
        migrations.AddField(
            model_name='element',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.image'),
        ),
        migrations.AddField(
            model_name='element',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.link'),
        ),
        migrations.AddField(
            model_name='element',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.list'),
        ),
        migrations.AddField(
            model_name='element',
            name='p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.paragraph'),
        ),
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('heading', 'heading'), ('list', 'list'), ('image', 'image'), ('link', 'link'), ('paragraph', 'paragraph'), ('line', 'line')], max_length=10),
        ),
    ]
