# Generated by Django 4.2 on 2023-05-31 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('heading', 'heading'), ('list', 'list'), ('image', 'image'), ('link', 'link'), ('paragraph', 'paragraph'), ('line', 'line'), ('frame', 'frame')], max_length=10),
        ),
        migrations.AddField(
            model_name='element',
            name='frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.iframe'),
        ),
    ]
