# Generated by Django 5.0.7 on 2024-11-24 06:13

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_iframe_alter_element_type_element_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_img',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='cover_images'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='cls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.topic'),
        ),
    ]
