# Generated by Django 5.0.7 on 2024-11-24 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_cover_img_topic_post_cls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
