# Generated by Django 5.0.7 on 2024-12-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
