# Generated by Django 5.0.7 on 2025-01-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.URLField(blank=True, null=True),
        ),
    ]
