# Generated by Django 4.1.7 on 2023-04-08 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100)),
                ('years', models.IntegerField()),
                ('about', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.SlugField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('background_img', models.ImageField(upload_to='cover_images')),
                ('full_name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='profile_pictures')),
                ('current_job', models.CharField(max_length=500)),
                ('about', models.TextField(max_length=2000)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=13)),
                ('fb', models.URLField(blank=True, null=True)),
                ('insta', models.URLField(blank=True, null=True)),
                ('tele', models.URLField(blank=True, null=True)),
                ('wp', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('mastery', models.IntegerField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.website')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=2000)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.website')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.ImageField(upload_to='Certificates')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.website')),
            ],
        ),
    ]
