# Generated by Django 4.1.7 on 2023-04-08 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_profile_coins'),
        ('portfolio', '0002_experience_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.profile'),
            preserve_default=False,
        ),
    ]
