# Generated by Django 4.1.7 on 2023-04-08 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_website_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Title',
            new_name='title',
        ),
    ]
