# Generated by Django 4.1.7 on 2023-04-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_title_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='background_img',
        ),
        migrations.AddField(
            model_name='website',
            name='cv_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
