# Generated by Django 4.2 on 2023-04-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_website_background_img_website_cv_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='adsense',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='analytics',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
