# Generated by Django 5.0.7 on 2024-11-24 06:11

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_website_adsense_website_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cert',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='Certificates'),
        ),
        migrations.AlterField(
            model_name='website',
            name='profile_pic',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='profile_pictures'),
        ),
    ]
