# Generated by Django 4.2.14 on 2025-01-05 18:39

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=10000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='posts')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes', to='portfolio.website')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='portfolio.website')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_profile', to='portfolio.website')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=10000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='comment_dislikes', to='portfolio.website')),
                ('likes', models.ManyToManyField(blank=True, related_name='comment_likes', to='portfolio.website')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.post')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_profile', to='portfolio.website')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
