# Generated by Django 4.2.14 on 2025-01-05 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_profile_coins'),
        ('portfolio', '0009_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.profile'),
        ),
    ]
