# Generated by Django 4.2.14 on 2025-01-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_website_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
