# Generated by Django 4.2.14 on 2025-03-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_post_image_alter_website_cv_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
