# Generated by Django 4.2.14 on 2025-03-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_website_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='unique_name',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
