# Generated by Django 4.2 on 2023-06-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='qr',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
